### ISSUE TITLE
App banner images

### ISSUE THREAD

**Issue by smileyhead** [mashers/3ds_hb_menu#41]
I had this idea. I don't mind if you don't/can't implement it. I just think it would be cool.
![scr_22_top_left](https://cloud.githubusercontent.com/assets/15932372/11284424/ec892ab2-8f09-11e5-98f1-0860025f11f8.png)

**Comment by ihaveamac** [comment]
I doubt models would happen, but maybe a larger image outside of the smdh? just my thoughts.

**Comment by TheMeq** [comment]
I like this idea, maybe a full background image which is slightly faded which can exist within the game directory or in a deprecate folder for cartridge games? This would appear behind everything else.

**Comment by mashers** [comment]
This is definitely possible. A PNG image within the 3dsx's folder would do the trick. I don't like the display of both the icon and the image though. It looks a bit cluttered in my opinion. We could certainly have the icon replaced by a larger image if it exists within the 3dsx folder. So, the folder structure would look something like:

/gridlauncher/folders/Emulators/blargSNES/blargSNES.3dsx
/gridlauncher/folders/Emulators/blargSNES/blargSNES.smdh
/gridlauncher/folders/Emulators/blargSNES/blargSNES-image.png

So the launcher will look for a file in the same folder as the 3dsx with the suffix -image.png, and if it's found then it will display this image rather than the icon data in the SMDH.

Does this sound like what you're asking for? By the way, 3D models and animated banners are almost definitely not an option, as they would most likely result in a large amount of code being added which would push the executable over the limit again.

**Comment by ihaveamac** [comment]
since this is pretty much Home Menu like now, maybe a sound that plays ~0.5 seconds after you select the icon. up to you though.

**Comment by mashers** [comment]
Do you mean when launching, or when highlighting the icon?

**Comment by ihaveamac** [comment]
highlighting the icon, similar to how the Home Menu does it. adding a delay before it tries to play the sound could stop delays when moving the cursor.

**Comment by TheMeq** [comment]
I would assume as the home brew launches, like when the 3DS logo appears when you run a game

**Comment by mashers** [comment]
Oh I see. So the select sound which plays already, but slightly delayed. Is that what you mean?

**Comment by TheMeq** [comment]
Ignore above comment lel

**Comment by ihaveamac** [comment]
well let’s start from here. as far as I’m aware, sounds end in .bin. a file like this would exist (likely a different name):

/gridlauncher/folders/Emulators/blargSNES/blargSNES-bannersound.bin

think of it like, again, at the Home Menu when you tap an icon to highlight it and it plays a little tune a second or so later.

**Comment by mashers** [comment]
Ohhh, you mean an individual one for each app?

**Comment by ihaveamac** [comment]
yes. does it make sense now?

**Comment by mashers** [comment]
Yes, perfect sense! I'm going to rename this issue and log a separate one for the banner sound.

**Comment by RedInquisitive** [comment]
@mashers is this help wanted? I could work on the banner/sounds when I get home today.

**Comment by smileyhead** [comment]
@mashers I didn't think I would even be noticed, but thank you for accepting my idea! :D
And thanks for everyone else for expanding it! :P

**Comment by smileyhead** [comment]
@mashers Also, to be closer to the original idea, could this use GIFs as well? :D

**Comment by mashers** [comment]
@RedInquisitive 
I've just got banner image loading actually. It checks for a file with the same name as the app and ending with -banner.png, and if it exists the path to the file is written to a char[] in menuEntry_s. When drawing the menuEntry, the selected entry has its banner path checked. If the file is a valid banner image (i.e. the correct size) then it's displayed instead of the icon.

@smileyhead 
No worries! As for using gifs, this would mean adding a gif decoding library to the launcher. Since PNGs are already used elsewhere, I would prefer to keep with the PNG format to avoid having to add unnecessary extra code/libraries.

**Comment by mashers** [comment]
Ok guys, how does this look? The banner image is actually 400x222 so fills the entire region under the status bar. This gives the potential to have different wallpapers or full-screen banners for apps. In this instance though, most of the image is transparent so the SNES is to the right of the text panel.

![hbl-grid-screenshot-3657014981](https://cloud.githubusercontent.com/assets/15194832/11300952/0941280e-8f8b-11e5-9757-94e971d71514.png)

**Comment by smileyhead** [comment]
@mashers
OMG this is so good! :D

**Comment by mashers** [comment]
Great! I'm going to push out an update to the online updater now.

**Comment by mashers** [comment]
Added in beta 115 :)
