### ISSUE TITLE
3DS game card inserted at title launcher does not act properly

### ISSUE THREAD

**Issue by ihaveamac** [mashers/3ds_hb_menu#54]
beta 119 - video demonstration: https://www.youtube.com/watch?v=8Mcmx85MhX0

* if a game card is inserted after opening the title selector, it will open the last selected homebrew instead.
* if a game card is in already, then taken out and re-inserted, it will work properly.
* if a game card is in already, then taken out and switched with a different one, it hangs at a red screen.

this happens regardless of HANS title booting, or what is chosen when SELECT is pressed.

**Comment by mashers** [comment]
Thank you for reporting these and for giving such detailed information about how to reproduce it! I suspect that the problem is with updating the title ID of the cart icon in the title menu. I will look into this tonight.

**Comment by mashers** [comment]
The issue here runs much deeper than I thought. The problem is with getting the title ID from the cart. When the cart is booted, the title ID is retrieved from the titleBrowser's title list. Unfortunately, it only seems to be possible to populate this list once, when the launcher starts up. This means several things:
* If no cart is inserted on launcher boot, no title entry for the cart will exist in the titleBrowser, so its title ID cannot be retrieved
* If a cart is subsequently inserted, its title ID will not be added to the titleBrowser
* If the cart was inserted from launcher boot and the cart was then changed, the titleBrowser will not be updated with the new cart's title ID

I have tried initialising new titleList objects when the cart is changed and getting the title ID that way, but everything I try seems to cause a hang.

**Comment by mashers** [comment]
Ahh, I'm having some success now. Rather than creating a titleList struct instance and trying to fill it, I'm calling the AM service directly through AM_GetTitleIdList() to get a single title ID with mediatype 2 (cart). I am now successfully able to get the current cart title ID when I change carts.

**Comment by mashers** [comment]
Ok, yup I'm now able to get the current title ID in both the main and title menus, whether changing carts or inserting a cart for the first time after opening the menu without a cart inserted. The problem I now have is that the target title information is still read from the titleBrowser by feeding in the title ID. If this doesn't exist (which it won't if the cart you're booting isn't the one which was inserted when the launcher was started up) then the launcher hangs on a red screen. So I need to look into getting the title information from the AM service using the title ID and constructing a new target title struct manually before booting.

**Comment by mashers** [comment]
Ahh it was easier than I thought. I can set the target_title's mediatype and title_id values directly rather than having to get them from the title browser or from AM! I've now got cart booting working from main and title grids with cart swapping and even if there is no cart present when opening the menu.

I've had to hard code the mediatype for now which means only carts work. I'm about to add a way of getting the mediatype so installed titles will work too.

**Comment by mashers** [comment]
DONE! :) Booting cart and installed titles now works with all cart insertion and removal combos. I need to do a bit of testing before releasing an update, but I think this is sorted now. I can't believe it took all evening!!! ;)

**Comment by ihaveamac** [comment]
I figured it wasn't getting the title ID properly but I didn't expect it to be this hard

**Comment by mashers** [comment]
Yeah it's been a tough bug to fix, but I think it's ok now. I'm about to push a beta update with the (hopeful) fix.
