### ISSUE TITLE
Interesting Audio bug

### ISSUE THREAD

**Issue by GuardianGallade** [mashers/3ds_hb_menu#77]
Whenever I move the cursor it says it is. As well as a long ticking sound. 
https://drive.google.com/file/d/0B1-SuyTZPXeeVFhEbUJlNGpEekk/view?usp=sharing

There is a video of it. It says "It is" in the singers voice instead of "Why cant it be perfect" and it is before the singer should even sing. This theme worked before I updated it as I made it. I am on the latest version. I have also noticed with all my old themes there is a weird ticking noise. Just like the one in the video when I move to select a icon...

**Comment by JJTapia19** [comment]
The ticking sound is due to the audio file having meta data. Try this and let us know if it works.

Remove any kind of metadata if your sound files includes them. In audacity, after selecting Export Audio and selecting your saving location an Edit Metadata window will open. Make sure to press on Clear and then OK to have clear sounds without any distortions.

**Comment by GuardianGallade** [comment]
I'll try it later this weekend as I do not have access to my mac atm. I'll let you know ASAP though

**Comment by mashers** [comment]
I'm closing this as it is due to the presence of the metadata in the audio file.
